name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Malavika-Gupta
          outputs: |
            ./output/github-contribution-grid-snake.svg
